USE master
GO
DROP DATABASE REVISAOTRIGGERS

CREATE DATABASE REVISAOTRIGGERS
go
USE REVISAOTRIGGERS
GO
-- CRIANDO TABELA -- 
CREATE TABLE TB_ALUNOS(
ID INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR (50),
MATRICULA VARCHAR(5)
);
GO

-- PROCEDURES -- 

-- INSERÇÃO -- 
CREATE PROCEDURE INSERCAOS(
@NOME VARCHAR (50),
@MATRICULA VARCHAR (5))
AS
BEGIN
INSERT INTO TB_ALUNOS(
NOME,
MATRICULA)
VALUES (
	@NOME,
	@MATRICULA );
END

-- UPDATE -- 	
GO
ALTER PROCEDURE ALTERACAO(
@ID int,
@NOME VARCHAR(50),
@MATRICULA VARCHAR(5))
AS
BEGIN
	UPDATE TB_ALUNOS SET
	NOME = @NOME,
	MATRICULA = @MATRICULA
	where ID = @ID

END

-- DELETE --
GO 
CREATE PROCEDURE APAGAR
@id int
AS
BEGIN
DELETE TB_ALUNOS WHERE ID = @id
END

-- TESTE -- 

-- PROCEDURE INSERCAOS -- 
EXECUTE INSERCAOS RENAN,123
EXECUTE INSERCAOS JOSE,1234
select * from TB_ALUNOS

--PROCEDURE UPDATE -- 
execute ALTERACAO 1,gabriel,123
select * from TB_ALUNOS
GO
-- PROCEDURE DELETE 
execute APAGAR 1
select * from TB_ALUNOS
go
-- FIM -- 

-- CRIAÇÃO TRIGGERS -- 
CREATE TRIGGER TGR_DUPLICACAO
ON TB_ALUNOS
AFTER INSERT
AS
BEGIN
	IF(EXISTS(SELECT MATRICULA FROM TB_ALUNOS
	GROUP BY MATRICULA
	HAVING COUNT(*)>1))
		BEGIN
			RAISERROR('MATRICULA JA EXISTE!',15,0)
			ROLLBACK
		END
	END
GO

-- TESTE TRIGGERS -- 
EXECUTE INSERCAOS RENAN, 1235
GO
EXECUTE INSERCAOS JOSE,1234
GO
SELECT * FROM TB_ALUNOS